In [13]:
import numpy as np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 1

In [14]:
v = np.arange(11)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2

In [16]:
m = np.zeros((3,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 3

In [32]:
m = np.random.randint(1, 11,(3,3))
m

array([[ 4,  4,  1],
       [ 6,  9,  4],
       [ 6, 10,  6]])

# 4

In [34]:
m = np.random.random((4,4))
m

array([[0.21921191, 0.97387381, 0.41340689, 0.78523171],
       [0.61603963, 0.97836183, 0.2990878 , 0.84356246],
       [0.06282831, 0.72088874, 0.80017917, 0.62805094],
       [0.81690258, 0.25835431, 0.78804092, 0.88257364]])

# 5

In [44]:
m1 = np.random.randint(1, 11, 5)
m2 = np.random.randint(1, 11, 5)
result = None

result = m1 - m2
print(f'operation: -\nm1={m1}\nm2={m2}\nresult={result}\n')

result = m1 + m2
print(f'operation: +\nm1={m1}\nm2={m2}\nresult={result}\n')

result = m1 * m2
print(f'operation: *\nm1={m1}\nm2={m2}\nresult={result}\n')


operation: -
m1=[5 4 9 2 1]
m2=[1 9 2 2 2]
result=[ 4 -5  7  0 -1]

operation: +
m1=[5 4 9 2 1]
m2=[1 9 2 2 2]
result=[ 6 13 11  4  3]

operation: *
m1=[5 4 9 2 1]
m2=[1 9 2 2 2]
result=[ 5 36 18  4  2]



# 6

In [51]:
v1 = np.random.random(7)
v2 = np.random.random(7)
print(v1)
print(v2)

np.dot(v1, v2)

[0.02376352 0.56349243 0.0098009  0.42229392 0.53302798 0.96249361
 0.79424399]
[0.97942506 0.40181907 0.35191144 0.09579505 0.29226195 0.62747762
 0.86122403]


1.7373483066888027

# 7

In [50]:
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2, 3))
print(m1)
print(m2)
np.dot(m1, m2)

[[ 8 10]
 [10  2]]
[[3 1 7]
 [3 9 2]]


array([[54, 98, 76],
       [36, 28, 74]])

# 8

In [49]:
m = np.random.randint(1, 11, (3, 3))
print(m)
np.linalg.inv(m)

[[4 3 4]
 [6 3 9]
 [7 2 7]]


array([[ 0.07692308, -0.33333333,  0.38461538],
       [ 0.53846154,  0.        , -0.30769231],
       [-0.23076923,  0.33333333, -0.15384615]])

# 9

In [56]:
m = np.random.random((4,4))
print(m)
m.T

[[9.91075824e-01 4.99301319e-02 5.26211186e-04 2.58278590e-01]
 [3.34493322e-01 5.83708081e-01 1.82394256e-01 7.62774541e-01]
 [1.61275158e-01 3.06862276e-01 2.83743081e-01 6.91530824e-01]
 [3.50324382e-02 6.75694492e-01 5.98903247e-01 9.65024450e-01]]


array([[9.91075824e-01, 3.34493322e-01, 1.61275158e-01, 3.50324382e-02],
       [4.99301319e-02, 5.83708081e-01, 3.06862276e-01, 6.75694492e-01],
       [5.26211186e-04, 1.82394256e-01, 2.83743081e-01, 5.98903247e-01],
       [2.58278590e-01, 7.62774541e-01, 6.91530824e-01, 9.65024450e-01]])

# 10

In [66]:
m = np.random.randint(1, 11, (3,4))
v = np.random.randint(1, 11, 4)
r = m*v

print(m)
print(f'\n{v}')
print(f'\n{r}')

[[ 7  3  4  8]
 [ 7  4  8  8]
 [ 7  3 10  8]]

[10  7  5  3]

[[70 21 20 24]
 [70 28 40 24]
 [70 21 50 24]]


# 11

In [68]:
m = np.random.random((2,3))
v = np.random.random(3)
r = m * v
print(f'{m}\n')
print(f'{v}\n')
print(r)

[[0.98346178 0.37272099 0.42561601]
 [0.33036748 0.35693616 0.95276359]]

[0.87619026 0.85214852 0.58110336]

[[0.86169964 0.31761364 0.24732689]
 [0.28946477 0.30416262 0.55365412]]


# 12

In [76]:
# DO NOT LOOK HERE
#---------------------------------------------------------------------------
def create_randints(first:int, last:int, size:tuple, quantity=1) -> list: 
    matrixes = list()
    for _ in range(quantity):
        matrixes.append(np.random.randint(first, last, size))
    return matrixes

def space():
    print(f'\n')
#----------------------------------------------------------------------------    

# TASK:
m1, m2 = create_randints(1, 11, (2,2), 2)
r = m1*m2

print(m1)
print(m2)
space()
print(r)


[[5 9]
 [4 9]]
[[8 6]
 [7 2]]


[[40 54]
 [28 18]]


# 13

In [78]:
m1, m2 = create_randints(1, 11, (2, 2), 2)
r = m1 + m2

print(m1)
print(m2)
space()
print(r)

[[10  2]
 [ 8  6]]
[[2 4]
 [6 6]]


[[12  6]
 [14 12]]


# 14

In [81]:
m = np.random.randint(1, 101, (5,5))
r = 0

for i in m:
    for el in i:
        r += el

print(r)

1114


# 15

In [82]:
m1, m2 = create_randints(1, 11, (4, 4), 2)
r = m1-m2

print(m1)
print(m2)
space()
print(r)

[[5 4 5 6]
 [9 8 8 6]
 [7 8 4 1]
 [1 1 6 3]]
[[1 5 2 3]
 [9 3 3 8]
 [1 2 6 9]
 [9 4 5 5]]


[[ 4 -1  3  3]
 [ 0  5  5 -2]
 [ 6  6 -2 -8]
 [-8 -3  1 -2]]


# 16

In [86]:
m = np.random.random((3,3))

r = None
sums = list()

for row in m:
    r = 0

    for el in row:
        r += el
        
    sums.append(r)

v = np.array(sums)

print(m)
space()
print(v[:, np.newaxis])

[[0.20162765 0.14325904 0.07156733]
 [0.73581531 0.10514435 0.51495192]
 [0.04665149 0.13074565 0.28022502]]


[[0.41645402]
 [1.35591158]
 [0.45762215]]


# 17

In [87]:
m = np.random.random((3,4))
r = m*m
print(m)
space()
print(r)

[[0.42103871 0.90595561 0.5369985  0.38712929]
 [0.77651886 0.25695176 0.40549706 0.40797794]
 [0.11742892 0.56234585 0.97850932 0.73327213]]


[[0.17727359 0.82075557 0.28836739 0.14986909]
 [0.60298153 0.06602421 0.16442786 0.166446  ]
 [0.01378955 0.31623286 0.95748048 0.53768801]]


# 18

In [88]:
v = np.random.randint(1, 51, 4)
r = v*v
print(v)
space()
print(r)

[ 2 36 21 19]


[   4 1296  441  361]
